### ISSUE TITLE
UWU-ify the docs as well

### ISSUE THREAD

**Issue by the-gremlin** [sgoudham/uwuifyy#11]

**Comment by sgoudham** [comment]
Good idea, I think adding a separate `README.uwu.md` would be good idea! Cause why not :P 
You should just be able to use the tool itself on the current `README.md` and tidy it up!

**Comment by 0warie** [comment]
> Good idea, I think adding a separate `README.uwu.md` would be good idea! Cause why not :P You should just be able to use the tool itself on the current `README.md` and tidy it up!

Currently in the process of doing just that!
