### ISSUE TITLE
Fix incorrect help message

### ISSUE THREAD

**Issue by sgoudham** [sgoudham/uwuifyy#7]
# The Problem 

Currently, the help message for `faces` is

`-f, --faces <VALUE>       The modifier for uwu faces e.g hello -> hewwo [default: 0.05]`

However, the example given does not demonstrate what that modifier actually does and instead represents the words modifier.

# The Fix 

The above help message should be updated to 

`-f, --faces <VALUE>       The modifier for uwu faces e.g hello ->  (^-^*)/ hewwo [default: 0.05]`

**Comment by Aman-Mandal** [comment]
Sir can I work on this ??

**Comment by sgoudham** [comment]
Hey! @Aman-Mandal 
Yeah go for it, it's a really simple documentation change as described above. Really appreciate it!

**Comment by Aman-Mandal** [comment]
Thankyouuu !! :)
